development:
application_id: xxxxxxxxxxxx
api_key: xxxxxxxxxxxxxxxxxxxxxxxx
secret_key: xxxxxxxxxxxxxxxxxxxxxxxx
canvas_page_name: MyApps
callback_url: your_callback_url
pretty_errors: true
set_asset_host_to_callback_url: true
tunnel:
public_host_username:
public_host:
public_port: 4007
local_port: 3000
server_alive_interval: 0

production:
application_id: xxxxxxxxxxxx
api_key: xxxxxxxxxxxxxxxxxxxxxxxx
secret_key: xxxxxxxxxxxxxxxxxxxxxxxx
canvas_page_name: MyApps
callback_url: your_callback_url
pretty_errors: true
set_asset_host_to_callback_url: true
tunnel:
public_host_username:
public_host:
public_port:
local_port:
server_alive_interval: 0
